name: Export to OSV format

on:
  push:
    branches: main

jobs:
  publish-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: osv
      - uses: actions/cache@v3
        with:
          path: ~/.cargo/bin
          key: rustsec-admin-v0.8.5
      - run: |
          VERSION="0.8.5"
          if ! ( rustsec-admin --version | grep -q "$VERSION" ); then
            cargo install rustsec-admin --force --vers "$VERSION"
          fi
          mkdir -p crates
          rustsec-admin osv crates
          # FIXME: hack to avoid committing advisories without an ID
          rm -f crates/RUSTSEC-0000-0000.json
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update OSV exported data" || true
          git push || true
